name: example
description: A simple example app for the sliding_up_panel package.

version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sliding_up_panel:
    path: ../

  flutter_map: ^0.5.0
  latlong: ^0.6.1
  cached_network_image: any

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true